on:
  # Trigger the workflow on push or PR to any branch
  push:
    paths:
      - '**/*.ipynb'
  pull_request:
    paths:
      - '**/*.ipynb'
    # don't trigger for draft PRs
    types: [ opened, synchronize, reopened, ready_for_review ]
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

name: Build
jobs:
  build:
    name: Notebook Test
    runs-on: ubuntu-20.04
    container:
      image: vnmd/neurodesktop:latest  # replace <your-docker-image> with your Docker image
      options: --user root
      ports: 
        - "8888:8888"
      volumes:
        - /neurodesktop-storage:/neurodesktop-storage
      env:
        NB_UID: "$(id -u)"
        NB_GID: "$(id -g)"
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: |
          python3 -m pip install nbmake pytest-xdist pytest-shell
      - name: Run qsmxt_example
        shell: bash
        run: |
            cd /home/jovyan/example-notebooks/structural_imaging && python -m pytest --pdb -srP -vv --nbmake-timeout=100000 --nbmake qsmxt_example.ipynb
      - name: Run sct_toolbox_example
        shell: bash
        run: |
            cd /home/jovyan/example-notebooks/structural_imaging && python -m pytest -srP -vv --nbmake-timeout=4000 --nbmake sct_toolbox_example.ipynb
      - name: Run sct_toolbox_example
        shell: bash
        run: |
            cd /home/jovyan/example-notebooks/functional_imaging && python -m pytest -srP -vv --nbmake-timeout=9000 --nbmake nipype_fsl_all_levels_flanker.ipynb