on:
  # Trigger the workflow on push or PR to any branch
  push:
    paths:
      - '**/*.ipynb'
  pull_request:
    paths:
      - '**/*.ipynb'
    # don't trigger for draft PRs
    types: [ opened, synchronize, reopened, ready_for_review ]
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

name: Build
jobs:
  build:
    name: Notebook Test
    runs-on: ubuntu-latest
    container:
      image: vnmd/neurodesktop:latest  # replace <your-docker-image> with your Docker image
      options: --user root
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run notebooks
        shell: bash
        run: |
            pip install pytest nbval
            chmod +x test_notebook.sh
            ./test_notebook.sh