# This workflows executes new or modified example notebooks.

name: test_changed_notebooks

defaults:
  run:
    shell: bash  # To override PowerShell on Windows

on:
  # Trigger the workflow on push or PR to any branch
  push:
    paths:
      - '**/*.ipynb'
  pull_request:
    paths:
      - '**/*.ipynb'
    # don't trigger for draft PRs
    types: [ opened, synchronize, reopened, ready_for_review ]
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

jobs:
  test_singularity_cvmfs:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Test singularity and cvmfs before pushing to neurocommand
      run: 
        /bin/bash .github/workflows/test_singularity_cvmfs.sh
        export SINGULARITY_BINDPATH='/cvmfs,/mnt,/home'

    - name: Install dependencies
      shell: bash
      run: |
          pip install nbmake pytest
    - name: Run qsmxt_example
      shell: bash
      run: |
          cd structural_imaging && python -m pytest -srP -vv --nbmake-timeout=100000 --nbmake qsmxt_example.ipynb