# This workflows executes new or modified example notebooks.

name: test_changed_notebooks

defaults:
  run:
    shell: bash  # To override PowerShell on Windows

on:
  # Trigger the workflow on push or PR to any branch
  push:
    paths:
      - '**/*.ipynb'
  pull_request:
    paths:
      - '**/*.ipynb'
    # don't trigger for draft PRs
    types: [ opened, synchronize, reopened, ready_for_review ]
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

jobs:
  test_singularity_cvmfs:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        repository: NeuroDesk/transparent-singularity
        fetch-depth: 0
    - name: Test singularity and cvmfs before pushing to neurocommand
      run: /bin/bash .github/workflows/test_singularity_cvmfs.sh
  run_notebook:
    needs: test_singularity_cvmfs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: yaananth/run-notebook@v2
        env:
          RUNNER: ${{ toJson(runner) }}
          SECRETS: ${{ toJson(secrets) }}
          GITHUB: ${{ toJson(github) }}
        with:
          notebook: "structural_imaging/qsmxt_example.ipynb"
          isReport: False
          poll: True