# This workflows executes new or modified example notebooks.

name: test_changed_notebooks

defaults:
  run:
    shell: bash  # To override PowerShell on Windows

on:
  # Trigger the workflow on push or PR to any branch
  push:
    paths:
      - '**/*.ipynb'
  pull_request:
    paths:
      - '**/*.ipynb'
    # don't trigger for draft PRs
    types: [ opened, synchronize, reopened, ready_for_review ]
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

jobs:
  test_notebooks:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        notebooks: [ "functional_imaging/nipype_fsl_all_levels_flanker.ipynb"]
    steps:
    - uses: actions/checkout@v3

    - name: Test singularity and cvmfs before pushing to neurocommand
      run: 
        /bin/bash .github/workflows/setup-cvmfs.sh

    - name: Install dependencies
      shell: bash
      run: |
        pip install nbmake pytest-xdist pytest-shell

    - name: Run ${{ matrix.notebooks }}
      shell: bash
      run: |
        export LD_PRELOAD=
        export APPTAINER_BINDPATH=/home/runner/work/example-notebooks/example-notebooks,/neurodesktop-storage
        export LMOD_CMD=/usr/share/lmod/lmod/libexec/lmod
        export MPLCONFIGDIR=/home/runner/work/example-notebooks/example-notebooks/matplotlib-mpldir
        export MODULEPATH=$(find /cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/ -maxdepth 1 -mindepth 1 -type d -exec realpath {} \; | tr '\n' ':')
        cd functional_imaging && python -m pytest -srP -vv --nbmake-timeout=100000 --nbmake nipype_fsl_all_levels_flanker