# This workflows executes new or modified example notebooks.

name: test_changed_notebooks

defaults:
  run:
    shell: bash  # To override PowerShell on Windows

on:
  # Trigger the workflow on push or PR to any branch
  push:
    paths:
      - '**/*.ipynb'
  pull_request:
    paths:
      - '**/*.ipynb'
    # don't trigger for draft PRs
    types: [ opened, synchronize, reopened, ready_for_review ]
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

jobs:
  test_notebooks:

    runs-on: ubuntu-20.04

    steps:  
      - name: Checkout Code
        uses: actions/checkout@v2       
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Test singularity and curl before pushing to neurocommand
        shell: bash
        run: 
          chmod +x cvmfs.sh
          /bin/bash cvmfs.sh
      - uses: yaananth/run-notebook@v2
        env:
          RUNNER: ${{ toJson(runner) }}
          SECRETS: ${{ toJson(secrets) }}
          GITHUB: ${{ toJson(github) }}
        with:
          notebook: "structural_imaging/qsmxt_example.ipynb"
          isReport: False
          poll: True