# This workflows executes new or modified example notebooks.

name: test_changed_notebooks

defaults:
  run:
    shell: bash  # To override PowerShell on Windows

on:
  # Trigger the workflow on push or PR to any branch
  push:
    paths:
      - '**/*.ipynb'
  pull_request:
    paths:
      - '**/*.ipynb'
    # don't trigger for draft PRs
    types: [ opened, synchronize, reopened, ready_for_review ]
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

jobs:
  select-runner:
    runs-on: ubuntu-22.04
    outputs:
      runner: ${{ steps.select_runner.outputs.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Select runner
        id: select_runner
        run: |
          if [ "${{ github.repository }}" = "neurodesk/example-notebooks" ]; then
            echo "runner=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner=ubuntu-22.04" >> $GITHUB_OUTPUT
          fi
          
  get-notebooks:
    runs-on: ubuntu-22.04
    outputs:
      notebook_list: ${{ steps.list_changed_notebooks.outputs.notebook_list }}
    steps:
    - uses: actions/checkout@v4
    - name: Find all notebooks with changes
      id: find_changed_notebooks
      uses: tj-actions/changed-files@v45.0.3
      with:
        path: "./books"
        files: |
          **/*.ipynb
          *.md
        dir_names_exclude_current_dir: "true"
    - name: Filter down to changed notebooks
      id: list_changed_notebooks
      run: |
        echo ${{ steps.find_changed_notebooks.outputs.all_changed_files }}
        changed_notebooks=$(echo "${{ steps.find_changed_notebooks.outputs.all_changed_files }}")
        
        notebook_list='['
        for NOTEBOOK in $(echo "${changed_notebooks}"); do
          notebook_list+="\"${NOTEBOOK}\","
        done
        notebook_list=$(sed '$s/,$//' <<< $notebook_list)
        notebook_list+=']'
        echo "notebook_list=${notebook_list}"
        echo "notebook_list=${notebook_list}" >> $GITHUB_OUTPUT

  test-notebooks:
    needs: [ select-runner, get-notebooks ]
    if: ${{ needs.get-notebooks.outputs.notebook_list != '[]' }}
    runs-on: ${{ needs.select-runner.outputs.runner }}
    container: 
      image: vnmd/neurodesktop:latest
      volumes:
        - /home/runner/:/home/
        - neurodesk-home:/home/jovyan
      options: --user root --privileged --shm-size=1gb
      env:
        NB_UID: 1001
        NB_GID: 1001
    timeout-minutes: 1500
    strategy:
      fail-fast: true
      matrix:
        notebooks: ${{ fromJson(needs.get-notebooks.outputs.notebook_list) }}
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
        mamba info --envs
        mamba install -c pypi -y papermill ghp-import

    - name: Run ${{ matrix.notebooks }}
      shell: bash
      timeout-minutes: 1500
      working-directory: ./books
      env: 
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo ${{ github.workspace }}
        echo $GITHUB_WORKSPACE
        export PATH=$HOME/.local/bin:$PATH
        echo "PATH=$PATH"
        echo "NOTEBOOK=$(basename -s .ipynb ${{ matrix.notebooks }})"
        echo "DIRNAME=$(dirname ${{ matrix.notebooks }})"
        echo "NOTEBOOK=$(basename -s .ipynb ${{ matrix.notebooks }})" >> $GITHUB_ENV
        echo "DIRNAME=$(dirname ${{ matrix.notebooks }})" >> $GITHUB_ENV
        DIRNAME=$(dirname ${{ matrix.notebooks }})
        echo "NOTEBOOK_OUTPUT=$DIRNAME/$(basename -s .ipynb ${{ matrix.notebooks }})_out.ipynb" >> $GITHUB_ENV
        NOTEBOOK_OUTPUT=$DIRNAME/$(basename -s .ipynb ${{ matrix.notebooks }})_out.ipynb
        echo "NOTEBOOK_OUTPUT=$NOTEBOOK_OUTPUT"
        ls -la "${{ matrix.notebooks }}"
        pwd
        papermill ${{ matrix.notebooks }} $NOTEBOOK_OUTPUT  --kernel python3 || exit 1

    - name: Check Notebook Execution Result
      if: always()
      env:
        ERROR_PATTERNS: "SyntaxError,Traceback,EOFError,NameError,Exception,ModuleNotFoundError,ImportError,OSError,FileNotFoundError,IndentationError,ValueError,TypeError,AttributeError,KeyError,ZeroDivisionError,RuntimeError,MemoryError,TimeoutError,IndexError,PermissionError,Cell execution timed out,Killed,FAILED,Failing,Aborted,Segmentation fault,Kernel Restarting,EnvironmentError,ConnectionError,HTTPError,NotJSONError"
      run: |
        # Check if output file exists
        execute_command "ls -la $NOTEBOOK_OUTPUT" 10
        
        # Split patterns into array
        IFS=',' read -ra ERROR_PATTERNS_ARR <<< "${ERROR_PATTERNS}"

        echo ""
        echo "Checking for error patterns in output (case-insensitive)..."
        ERROR_FOUND=0
        for pattern in "${ERROR_PATTERNS_ARR[@]}"; do
            if error_lines=$(execute_command "grep -i '${pattern// /}' $OUTPUT_NAME" 5) && [ -n "$error_lines" ]; then
                echo "⚠️ Found error pattern: $pattern"
                echo "Error lines: $error_lines"
                ERROR_FOUND=$((ERROR_FOUND + 1))
            fi
        done
        
        # Check papermill metadata for exceptions
        exception=$(echo "$resp" | jq -r '.content.metadata.papermill.exception // empty')
        if [[ -n "$exception" ]]; then
            echo "⚠️ Found papermill exception: $exception"
            ERROR_FOUND=$((ERROR_FOUND + 1))
        fi

        echo "ERROR_FOUND=$ERROR_FOUND" >> $GITHUB_ENV
        echo "ERROR_PATTERNS_TOTAL=${#ERROR_PATTERNS_ARR[@]}" >> $GITHUB_ENV

        if [ $ERROR_FOUND -eq 0 ]; then
            echo "✅ Notebook execution successful! ($ERROR_FOUND/${#ERROR_PATTERNS_ARR[@]} error patterns found)"
            echo "NOTEBOOK_SUCCESS=true" >> $GITHUB_ENV
        else
            echo "❌ Notebook execution may have failed ($ERROR_FOUND/${#ERROR_PATTERNS_ARR[@]} error patterns found)"
            echo "NOTEBOOK_SUCCESS=false" >> $GITHUB_ENV
        fi

    - name: Clean build dir
      run: |
        rm -rf /home/ubuntu/actions_github_pages_*

  build-structure:
    if: ${{ needs.test-notebooks.result != 'failure' }}
    needs: [ test-notebooks ]
    runs-on: ubuntu-22.04
    container: 
      image: vnmd/neurodesktop:latest
      volumes:
        - /home/runner/:/home/
        - neurodesk-home:/home/jovyan
      options: --user root --privileged --shm-size=1gb
      env:
        NB_UID: 1001
        NB_GID: 1001
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
        mamba install -c pypi jupyter-book ghp-import

    - name: Run all
      shell: bash
      working-directory: ./books
      env: 
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export PATH=$HOME/.local/bin:$PATH
        /bin/bash ../.github/scripts/write-toc-entry.sh
        sed -i 's/execute_notebooks: .*/execute_notebooks: off/' _config.yml
        cat _config.yml
        jb build .


    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4.0.0
      if: github.event_name != 'pull_request'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./books/_build/html
        keep_files: true
        cname: www.neurodesk.org
